### ISSUE TITLE
建议开启 RSS

### ISSUE THREAD

**Issue by CyrusYip** [residualsun1/Guozheng#2]
没有 RSS，读者就没法订阅网站。

**Comment by residualsun1** [comment]
等文章写多一点再整个RSS:-)

**Comment by CyrusYip** [comment]
我看你在统计之都和GitHub页面都没写你两个博客的地址，是不是还没准备好公开？

我觉得两个博客太分散了，有些文章在两边都有出现，合并起来大概更能[集中影响力](https://yihui.org/cn/2019/03/influence-focus/)，读者评论也能集中。你似乎还在探索 quarto 和 blogdown 网站，可能我说的为时尚早了，加油继续写吧！

**Comment by residualsun1** [comment]
> 我看你在统计之都和GitHub页面都没写你两个博客的地址，是不是还没准备好公开？

嗯，我感觉第一个博客越写越不想公开，就打算把它当作唯一的自留地。

> 我觉得两个博客太分散了，有些文章在两边都有出现，合并起来大概更能[集中影响力](https://yihui.org/cn/2019/03/influence-focus/)，读者评论也能集中。你似乎还在探索 quarto 和 blogdown 网站，可能我说的为时尚早了，加油继续写吧！

两个博客运营起来确实挺费力，不过一方面我还在探索quarto和blog，另一方面我其实不大在意博客的影响力，因为现在更多是写给自己看，同时满足自己折腾的劲头（大学生还是挺闲的哈哈）。我初步的打算是把两个博客分成两个方向，blogdown作为日记，写一些日常和心路历程，随意一些，偶尔可能会有一些情绪化的内容，所以不想公开，留给自己和少数几个朋友看就好了^^；quarto则想把它发展成正式写作，尽量向一些非虚构写作、深度写作和类似社会评论的方向靠拢，以后如果要展示自我或许可以拿出来。

quarto应该会写得很慢，但我会保持blogdown的写作频率。趁着折腾念头还比较强，时间也比较多，先继续写着:-)，之后看看情况会咋样。但如果要排出重要性，blogdown对我肯定是最重要的。
